import Head from 'next/head'
import Layout from '../components/Layout'
import '../styles/globals.scss'
import icon from '../public/icon.jpg'
import { useEffect,useState,createContext } from 'react'
import { DialogContainer } from '../components/Dialog'
import UserContext from '../components/UserContext'
import { useRouter } from 'next/router'
import {getUser} from '../services/User.service'
import User from '../models/User'
import { cookies } from 'next/headers'

function MyApp({ Component, pageProps }) {

  const getLayout = Component.getLayout || ((page) => <Layout>{page}</Layout>)
  const [userContext, setUserContext] = useState(null);
  const [redirectState, setRedirectState] = useState(false);
  const router = useRouter();

  useEffect(() => {
    /*(async () => {
      const res = await fetch('/api/version.php');
      if (res.ok) {
        const data = await res.text();
        const dev_info = document.getElementById('dev_info');
        dev_info.innerHTML = "<p>" + data + "</p>";
      }
    })();
    return () => {

    }; */

    //TODO: get user from server
    const mockUser = {
      username: 'test',
    };

    const user:User | null = null;
    console.log("cookies",document.cookie);

    //const tmpCookies:string|undefined = cookies().get('access-token')[0];
      getUser().then((res) => {
        console.log("result",res);
      })
      .catch(async (err) => {
        console.error("Error",err);
      });

    
    if (user == null && window.location.pathname != '/user/login/' && window.location.pathname != '/user/register/') {
      router.push('/user/login/');
      setRedirectState(true);
    }
    else
    setUserContext(user);
    

  }, []);

  return (
    <UserContext.Provider value={{userContext, setUserContext}}>

    <Head>
        <title>graduater</title>
        <meta name="description" content="Generated by create next app & export" />
        <link rel="icon" href={icon.src} />
      </Head>
      <DialogContainer />

      <div className='background_img'></div>
      <div>
        <div id="dev_info"><p>No build number</p></div>
        {
          getLayout(<div className="main_container"><Component {...pageProps} /></div>)
        }
      </div>

    </UserContext.Provider>



  )
}

export default MyApp
