name: "Deploy"

on:
  push:
    branches:
      - master

jobs:
  build:
    name: "Deploy project on live-dev server"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          cat >>~/.ssh/config <<END
          Host deployment_server
            HostName ${{ secrets.SSH_SERVER }}
            User ${{ secrets.SSH_USERNAME }}
            IdentityFile ~/.ssh/deploy_key
            StrictHostKeyChecking no
          END

      - name: Check SSH Connection
        run: ssh deployment_server 'echo "SSH connection successful"'

      - name: Deploy script
        run: ssh deployment_server 'bash ~/school_collab/deploy_script.sh'
