name: Deploy to Server

on:
  push:
    branches:
      - master  # Set this to the branch that triggers deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.2
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH and Deploy
      env:
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        SSH_SERVER: ${{ secrets.SSH_SERVER }}
      run: |
        ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_SERVER 'bash -s' < deploy_script.sh
