name: Deploy CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Deploy
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Pull project
      run: cd /home/github/school_collab & git pull
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run deploy
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: 20.203.131.180
          REMOTE_USER: github
          EXCLUDE: "/dist/, /node_modules/"
