name: remote ssh command
on: 
  push:
    branches:
      main
      
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Connect to deploy server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SHH_PRIVATE_KEY }}
        script: sh deploy.sh
