name: remote ssh command
on: 
  push:
    branches:
      main
      
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ls -a via ssh
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: cd /home/github/school_collab & sudo sh deploy.sh
        host: ${{ secrets.HOST }}
        username: github
        privateKey: ${{ secrets.SSH_PRIVATE_KEY}}
