on: [push]
      
jobs:
  build:
    name: "Deploy project on dev server"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: github
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: 20.203.131.180

      - name: Check SSH Connection
        run: ssh staging 'echo "It works!"'

      - name: Pull project code
        run: ssh staging 'sudo git -C ./school_collab pull'

      - name: Deploy next project
        run: ssh staging 'npm --prefix ./school_collab run deploy'
        
      - name: Create PHP API folder 
        run: ssh staging 'mkdir ./school_collab/out/api'
        
      - name: Copy PHP files
        run: ssh staging 'cp -a ./school_collab/api ./school_collab/out/api'
